AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 connector to PhotoOpsAI platform

Parameters:
  ServiceName:
    Type: String
    Description: "Name of service"
    Default: "PhotoOpsAIConnectorS3"

  ServiceEnv:
    Type: String
    Description: "Name of deployment environment"
    Default: "prime"

  PhotoOpsAIAccountId:
    Type: String
    Description: "AWS account ID for PhotoOpsAI"
    Default: "355364402302"

  PhotoOpsAISnsTopicArn:
    Type: String
    Description: "ARN of PhotoOpsAI SNS Topic"
    Default: "arn:aws:sns:us-east-1:355364402302:PhotoOps-tom-PhotoOpsIngestTopic-MN59XIN0X5CB"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "photoopsai-${ServiceEnv}-${AWS::AccountId}"
      Tags:
        # NOTE: Used by PhotoOpsAI to figure out owner of bucket which is not
        # otherwise possible using AWS APIs.
        #
        # FIXME: We can get rid of this. Bucket and key will be unique enough.
        - Key: "x-PhotoOpsAI-AWS-AccountId"
          Value: !Sub "${AWS::AccountId}"
      NotificationConfiguration:
        TopicConfigurations:
          - Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: "images/"
            Topic: !Ref PhotoOpsAISnsTopicArn

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Id: "Read"
        Version: "2012-10-17"
        Statement:
          - Sid: "PhotoOpsAIGetData"
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${PhotoOpsAIAccountId}:root"
            Action: s3:GetObject
            Resource: !Sub "${S3Bucket.Arn}/*"
          - Sid: "PhotoOpsAIGetBucketTags"
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${PhotoOpsAIAccountId}:root"
            Action: s3:GetBucketTagging
            Resource: !Sub "${S3Bucket.Arn}"


Outputs:
  S3BucketName:
    Description: "Name of S3 Bucket"
    Value:
      Ref: S3Bucket
